server:
  # 服务端口
  port: 8099
spring:
  # 数据库连接设置
  datasource:
    # h2数据库驱动
    driver-class-name: org.h2.Driver
    # h2数据库链接地址
    url: jdbc:h2:mem:demo
    password: sa
    username: sa
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  # h2数据库配置
  h2:
    console:
      enabled: true
      path: /h2

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  #http请求的header中的key
  header-name: Authentication
  #密钥
  secret: aabbcc
  #勾选记住我允许的token有效期30天（秒）
  max-duration: 2592000

